---
driver:
  name: vagrant
  customize:
    memory: 1024

platforms:
  - name: web1
    driver_plugin: vagrant
    driver:
      box: ubuntu/trusty64
      network:
        - ["private_network", {ip: "10.105.0.50"}]

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_url: https://www.chef.io/chef/install.sh
  client_rb:
    environment: dev

suites:
  - name: default
    run_list:
      - role[tornado-webserver]
